### PR TITLE
Resharper 2016.1 compatibility

### PR DESCRIPTION
**Pull request by jaytonic**
The code now check what command should be used to do the silent cleanup
since Resharper changed the name of this commands since its version
2016.1

### CODE REVIEW

**Comment by Nargzul** [comment]
This is related to the issue #20

**Comment by robertbaker** [comment]
+1 (mobile lacks reactions :( )

**Comment by PombeirP** [comment]
Published as 1.2.4. Thanks for the contribution!

**Comment by jgrossrieder** [comment]
@PombeirP Thank you for the reintegration ;)

**Pull request closed without merging**
